### ISSUE TITLE
PHP 5.4 support official?

### ISSUE THREAD

**Issue by LostKobrakai** [crysalead/kahlan#108]
In the README there's still php 5.5 stated as minimum version. Not sure if this is intentional.

**Comment by jails** [comment]
PHP 5.4 has been dropped in 1.2.0, but has been reintroduced in 1.3.0 and 2.0.0 because I won't be able to support the 1.1.x branch anytime soon and I wanted to avoid to much trouble for 1.1.x users.
So the current version of Kahlan works with PHP 5.4 but it's not an official support and it may be dropped in a futur version if it became a limiting factor again.

**Comment by LostKobrakai** [comment]
Thanks for the clarification, was just a bit confused reading the changelog.
