### ISSUE TITLE
How to run a single Spec file in Kahlan

### ISSUE THREAD

**Issue by shivshankarsomu** [crysalead/kahlan#125]
@jails @m1ome 

How to run a single Spec file in Kahlan because when **./bin/kahlan ** it runs all spec files.

Please help me with that.

One more I have more than PHALCON MVC 50 models so I wanted a load a JSON with a sample data for the Stubs .

Can you please tell me how can I do that.

**Comment by m1ome** [comment]
@shivshankarsomu you can use something like that: 
```
./bin/kahlan --pattern="spec/Suite/SuiteSpec.php"
```

It's example how to run `spec/Suite/SuiteSpec.php` only. (from **Kahlan** spec suite)

**Comment by m1ome** [comment]
@shivshankarsomu about your second question: you need to thing about your stub mechanism by yourself, and seeding your data of course. Straight is just to have a database fixtures that will prune DB before every test run and then populate it with a new data.

**Comment by jails** [comment]
Use the [focused mode](https://github.com/crysalead/kahlan/blob/master/docs/pro-tips.md#use-the-focused-mode) i.e. `fdescribe`, `fcontext` or `fit` to only run the spec you are working on or use the `--pattern` option.

For your second question just use a real database. Stubbing models to return some JSON data is definitely not the good option imo. Any kind of abstraction you can acheive with Stubs returnning JSON for models will ends up to something limitated, incomplete and hacky.

And if it's for some performance issues simply configure your test env to use a mysqli database instead of a mysql/postgresql database.
