### ISSUE TITLE
Expect matchers chaining.

### ISSUE THREAD

**Issue by m1ome** [crysalead/kahlan#13]
1. It's nothing said about chaining in documentation, and it's kinda bad.
2. If you look on [Leo](http://peridot-php.github.io/leo/) it's bit more eye-candy when you write it.

In example:

**Kahlan**

```php
$a = [1, 2, 3];
expect($a)->toBeA('array');
expect($a)->toContain(2)->toContain(3);
```

**Leo**

```php
$a = [1, 2, 3];
expect($a)->to->be->a('array')->and->to->contain([2, 3]);
```

It's more human-readable i think

**Comment by jails** [comment]
Even if not the best test framework, Jasmine tends to be one of the most popular client side. Since I'm switching a lot between JS & PHP code, I didn't want to change my mind to write specs every time. So that's why I started with the the Jasmine naming.

Each convention is a matter of choice and everybody has his own preference on this subject. So I prefered to follow a convention which won his spurs.

**Comment by m1ome** [comment]
:+1:  ok, just wanna hear your opinion.
