### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by shivshankarsomu** [crysalead/kahlan#133]
@m1ome @jails 
My test Suite has more than 9000 test cases which runs at a time by **KAHLAN** command in my staging enviroment.

But after like 80% of test cases it gives a segmentation fault becauses PHP allowable memory limit of  **128MB** 
I dont want to change my PHP configuration both in ini file or in runtime .

Is there any other to solve this issue so that it doesnot take RAM greater than 128MB 

Waiting for your reply

**Comment by jails** [comment]
It might be caused by your code, a memory leak, or anything else.
Increasing the memory limit doesn’t sound bad to me if it’s still reasonable. Otherwise, you might want to use a profiling tool to see why the memory usage grows and if it’s unexpected regarding the size of your test suite.
You can also try to force garbage collection using `gc_collect_cycles()` in an `afterEach()`.
But there's not enough information here to conclude that's a Kahlan's issue.
So feel free to open this issue back if your investigation shows that the memory leak is specifically related to Kahlan.

**Comment by pittikroh** [comment]
Hi,
we got the same problem. But even when we extend the allowed memory, we will have the same problem in some weeks.
I monitored how the memory usage grows during the tests. It looks like kahlan is not unblocking the memory after each spec file. The used memory is growing with every spec file. Is there a possibility to free the memory after running each spec file?
Your suggested workaround with gc_collect_cycles() in an afterEach() has no effect.

**Comment by jails** [comment]
Hi,
Unfortunately I don't think it's possible. Also code coverage in PHP is consuming a lot of memory (whatever you are enabling it with xdebug or phpdbg). However I'm working on some parallel testing right now. It'll probably be the only sustainable way to run big specs suite w/o running out of memory at some point.

In the last Kahlan version you can do things like:
```php
./bin/kahlan --part=1/3
./bin/kahlan --part=2/3
./bin/kahlan --part=3/3
```
Kahlan will automatically split the specs in different parts sot it can run the specs part by part.
I didn't updated the documentation right now since I need to add an additional step so we can merge coverage results all together.
