### ISSUE TITLE
Redeclaring the same class

### ISSUE THREAD

**Issue by artur-dev** [crysalead/kahlan#136]
I have problem when running kahlan tests:
```
PHP Fatal error:  Cannot redeclare class Doctrine\Common\Annotations\Annotation\Target in /.../vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/Annotation/Target.php on line 32
```
It happens when I try to use JMS Serializer from Symfony. It looks like kahlan loads one version of class from /tmp/kahlan/..../Target.php and then Doctrine is doing require_once on it's own version. Is there any way I could avoid this problem? Does it have to patch it?

**Comment by m1ome** [comment]
@artur-dev can you provide MVP of this code? I mean some boilerplate which will fail with this use-case?

**Comment by jails** [comment]
There's a couple of way to deal with code relying on `require_once` instead of Composer. But I'll need more detail about the flow. When `Target` is loaded for the first time, which file is doing the `require_once`. So any more detail are welcome.
But imo opening a Doctrine issue will also be a good idea since `require_once` doesn't really belongs to PHP best practices.

**Comment by artur-dev** [comment]
showcase https://github.com/artur-dev/test-redeclare

**Comment by jails** [comment]
Yeah the issue is related to the `DocParser`. `Target` is firstly loaded here https://github.com/doctrine/annotations/blob/6a6bec0670bb6e71a263b08bc1b98ea242928633/lib/Doctrine/Common/Annotations/DocParser.php#L138 through composer so Kahlan cached it in `/tmp/kahlan/..../Target.php, then it has been explicitly required using `__DIR__` here https://github.com/doctrine/annotations/blob/6a6bec0670bb6e71a263b08bc1b98ea242928633/lib/Doctrine/Common/Annotations/DocParser.php#L472.

It would have been possible to monkey patch the `require_once` statement but since it's unlikely there is a need to stub or patch this part so I would recommand to simply tell Kahlan to ignore everthing under the `Doctrine\Common\Annotations` namespace.

Using the following as `kahlan-config.php` file should solve your issue:
```php
<?php
use Kahlan\Filter\Filter;

Filter::register('exclude.namespaces', function ($chain) {
    $defaults = ['Doctrine\Common\Annotations'];
    // Simply to not override excluded namespaces passed through the `--exclude` option
    $excluded = $this->args()->get('exclude');
    $this->args()->set('exclude', array_unique(array_merge($excluded, $defaults)));
    return $chain->next();
});

Filter::apply($this, 'interceptor', 'exclude.namespaces');
```

**Comment by artur-dev** [comment]
Thanks a lot!

**Comment by paperscissors** [comment]
Is this resolved in master at this point? When I try to use that example `kahlan-config.php` file I get the following error:

`PHP Fatal error:  Call to undefined method Kahlan\Cli\Kahlan::args() in kahlan-config.php on line 5`

**Comment by samsonasik** [comment]
`args()` was changed to `commandLine()`, see https://github.com/kahlan/kahlan/commit/f0edf197109b55e1915ddd1d199552768b6cb845
