### ISSUE TITLE
Do we have something like PHPUnit DataProviders for Kahlan

### ISSUE THREAD

**Issue by Ilyes512** [crysalead/kahlan#146]
So I was wondering if it was possible to mimic dataproviders like they have on PHPUnit. The idea is that you have a data set and an expected value and you basically execute the same test with different input and expected output.

I think I could use foreach inside a spec, but was wondering if there where nicer ways?

More info:
https://phpunit.de/manual/current/en/writing-tests-for-phpunit.html#writing-tests-for-phpunit.data-providers

**Comment by jails** [comment]
It's an interesting question but I don't have a clear answer. All existing alternatives in a style spec syntax are either not elegant or not better than a simple `foreach`.

In my opinion if "Data Providers" sound like a "time saver feature", it have the same drawbacks as writing big tests cases with a lot of assertions/expectations inside.

To be useful each entry provided by your "Data Providers" should run a different path inside your code otherwise a single entry would have been enough.
So if different paths are tested, it means that a spec with a specific meaning (i.e an appropriate spec message) can be extracted to identify a single use case per data entry.

It'll probably take more time but it'll help to maintain your test suite in the long run.

Anyway for legacy code where it's not really possible to follow code paths or meaning, I guess just throwing a bunch of random data can be useful. So in this case I would probably use a foreach **outside** a spec and passing parameters through function's `use` statement.

**Comment by Ilyes512** [comment]
Not sure what you mean by `So in this case I would probably use a foreach outside a spec and passing parameters through function's use statement.`. Could you clarify this with an example :)?

**Comment by jails** [comment]
Which the PHPUnit example is would do:

```php
describe("data provider example", function() {

    $data = [
        [0, 0, 0],
        [0, 1, 1],
        [1, 0, 1],
        [1, 1, 3]
    ];

    foreach($data as $values) {
        list($a, $b, $expected) = $values;

        it("adds {$a} and {$b} correctly", function() use ($expected, $a, $b) {

            expect($a + $b)->toBe($expected);

        });
    }

});
```

Customizing spec messages with a meaningful description of the spec will help to understand what's going on when a spec doesn't pass any more.

**Comment by jails** [comment]
I used this pattern once, when I needed to run a bunch of specs through multiple database drivers for example:
https://github.com/crysalead/chaos-database/blob/master/spec/Suite/SchemaSpec.php#L18-L23

**Comment by jails** [comment]
And I would also move this data in a kind of fixture class.

```php
use MyProject\Spec\Fixture\SomeFixture;

describe("data provider example", function() {

    foreach(SomeFixture::someSampleData() as $values) {
        list($a, $b, $expected) = $values;

        it("adds {$a} and {$b} correctly", function() use ($expected, $a, $b) {

            expect($a + $b)->toBe($expected);

        });
    }

});
```

**Comment by theofidry** [comment]
@jails your workaround can work, but it decrease considerably the readability: 

your solution:

```php
describe("data provider example", function() {

    $data = [
        [0, 0, 0],
        [0, 1, 1],
        [1, 0, 1],
        [1, 1, 3]
    ];

    foreach($data as $values) {
        list($a, $b, $expected) = $values;

        it("adds {$a} and {$b} correctly", function() use ($expected, $a, $b) {

            expect($a + $b)->toBe($expected);

        });
    }

});
```

in PHPUnit:

```php
/**
  * @dataProvider provideOperandForAdd
  */
public function test_it_adds_a_and_b_correctly($a, $b, $expected)
{
    $this->assertEquals($expected, $a + $b);
};

public function provideOperandForAdd()
{
    yield [0, 0, 0];
    yield [0, 1, 1];
    yield [1, 0, 1];
    yield [1, 1, 2];
}
```

and if you want a custom message for a specific set of data, you can always do `yield 'zeros everywhere' => [0, 0, 0];`

**Comment by m1ome** [comment]
@theofidry It looks like it can be achieved through a custom Matcher, and `yield` is restricting us to some high PHP versions.

**Comment by theofidry** [comment]
@m1ome I may have missed something but I don't see how a custom matcher which is about testing a value can solve this problem which is about running the same describe block with a different set of data.

As for the `yield` keyword, it is available since PHP 5.5 which matches this library requirement (PHP 5.5+).

**Comment by m1ome** [comment]
@theofidry currently Kahlan can run on 5.4, 5.5 is just more for a future stuff (https://travis-ci.org/crysalead/kahlan/jobs/154687652). 
It looks like understand wrong, your example contains just one assertion and it's confused me, if in e.g. it have 2-3 assertions.

I don't know why you say that @jails example is bad then.
In e.g. Golang will also be same way:

```go
package math

import "testing"

type testpair struct {
  values []float64
  average float64
}

var tests = []testpair{
  { []float64{1,2}, 1.5 },
  { []float64{1,1,1,1,1,1}, 1 },
  { []float64{-1,1}, 0 },
}

func TestAverage(t *testing.T) {
  for _, pair := range tests {
    v := Average(pair.values)
    if v != pair.average {
      t.Error(
        "For", pair.values,
        "expected", pair.average,
        "got", v,
      )
    }
  }
}
```

It much more cleaner for a new library user to understand something @jails wrote than something that wrote you, IMO.

**Comment by jails** [comment]
@theofidry you can also make it more readable by introducing your own DSL if it's a pattern your are using frequently.

In the `kahlan-config.php` config file for example you can add the following function:
```php
<?php
use Kahlan\Util\Text;
use Kahlan\Suite;

function with_provided_data_it($message, $closure, $provider = [], $timeout = null, $scope = 'normal')
{
    $data = is_callable($provider) ? $provider() : $provider;
    foreach ($data as $values) {
        Suite::current()->it(Text::insert($message, $values), function() use ($closure, $values) {
            call_user_func_array($closure, $values);
        }, $timeout, $scope);
    }
}
```

Then your spec will look like:
```php
<?php
describe("data provider example", function() {

    with_provided_data_it("adds {:0} and {:1} and expect to be {:2}", function($a, $b, $expected) {
        expect($a + $b)->toBe($expected);
    }, function () {
        yield [0, 0, 0];
        yield [0, 1, 1];
        yield [1, 0, 1];
        yield [1, 1, 2];
    });

});

Like I said earlier I don't know what should be the best approach, but Kahlan is imo flexible enough to find your own way do deal with data providers.

**Comment by theofidry** [comment]
@m1ome

>@theofidry currently Kahlan can run on 5.4, 5.5 is just more for a future stuff (https://travis-ci.org/crysalead/kahlan/jobs/154687652). 

My comments was based on [the readme](https://github.com/crysalead/kahlan#requirements) but indeed the [composer.json](https://github.com/crysalead/kahlan/blob/master/composer.json#L12)  and Travis seems to indicate otherwise.

An alternative to the `yield` keyword is to used arrays, like the old way anyway. `yield` provides just a more readable way for data providers.

>I don't know why you say that @jails example is bad then.

I didn't say it was "bad", I gave the difference between how it is done in Hahlan and how it is done in PHPUnit.

>In e.g. Golang will also be same way

I could argue that you can have data providers in JUnit in Java as well... But this is irrelevant, we are not talking of a language feature but of a testing framework feature.

>It much more cleaner for a new library user to understand something @jails wrote than something that wrote you, IMO.

I can't say it is "cleaner", to me the example with a data provider makes it much easier to read. But this is my opinion and we may just agree to disagree on that... However I agree with you on one point: it may be slightly harder to understand because you have to rely on a new feature which is data providers. But it's a very popular concept so it's not a big deal IMO.

@jails I don't doubt there is acceptable workarounds. Kahlan is not the only library having this issue, I don't know any "describe-it" testing framework that supports data provider like described above to be honest.

I am not saying this is a bad thing not to have it, but if you don't want to add support for it then you should just simply say so and close this issue :)

IMO this is were I would use a framework like PHPUnit: you have features like data providers, groups, control on timing or memory consumption. From what I understood this library does not plan to support all of those features but to stay more simple and provide a more elegant syntax, which is doable because *it is* simpler.

**Comment by jails** [comment]
I think the "describe-it" philosophy is different not restrictive. Last year I wanted to do an experiment and using Kahlan for doing some [E2E tests](http://radify.io/blog/end-to-end-functional-testing-with-kahan/). So I created my own DSL to make my tests readable according to my need. The problem with features is they are restrictives to an implementation while the "describe-it" philosophy opens door of freedom. I personally gave up PHPUnit because of lack of freedom **and** missing features. So I don't mind writing a couple of line of code when I've a specific need in mind.

**Comment by jails** [comment]
To conclude, I think introducing a new statement (like the `with_provided_data_it()` above) is the way to go here. So I'll close this issue now but feel free to open it up again if you find a better alternative which respect the spec style philosophy.

**Comment by thiagodp** [comment]
Please add the [example](https://github.com/kahlan/kahlan/issues/146#issuecomment-242127518) from @jails to the Documentation.
