### ISSUE TITLE
[BUG/ISSUE] Before and BeforeEach.

### ISSUE THREAD

**Issue by m1ome** [crysalead/kahlan#18]
I have a problem if i do something like that:

```php

describe("Top level", function() {
 
    beforeEach(function() {
        $this->a = 10;
    });

    describe("Sub level", function() {
    
        before(function() {
              $this->b = 100;
        });    

        iit("should do something", function() {
             var_dump($this->a);
        });

    });

});

```

And it will say something like `Undefined variable` and throw Exception.
It's seems like iit working bad with nested scopes?

**Comment by jails** [comment]
Just copy pasted your code and the result is:
```php
int(10)
```
And it's not like just me. Just have https://github.com/jails/temp/commit/5c7287b482fd7b036256f0a2457ef5685ae4e524 runned on travis and it worked fine for all PHP version (https://travis-ci.org/jails/temp/jobs/49310087). None of them generated an `Undefined variable` Exception.

Note sur to understand what's going on with your environement. If you find the root cause, feel free to keep me updated because I really would like to know where the problem lies.
