### ISSUE TITLE
Removing "minimum stability".

### ISSUE THREAD

**Issue by m1ome** [crysalead/kahlan#22]
Maybe you should remove minimum stability flag?
As i could see every your package in kahlan dep could be released into some initial version like 1.0.0.

**Comment by jails** [comment]
That was my initial objective, but due to [a composer "glitch"](https://github.com/composer/composer/issues/3673) it tends to be a quite painful to tag Kahlan dependencies. I realized I'll need to maintain a `COMPOSER_ROOT_VERSION` for each dependency and since it's not possible to set it with a `COMPOSER_ROOT_VERSION=*` value, it'll require a couple of back and forth when Kahlan dependencies will be bumped up in the futur. So I'll need to check wisely all dependencies before tagging it and entering into the dark side of composer.

**Comment by m1ome** [comment]
As i see it's a workaround when composer meet's up a circular deps. You can resolve it not using a composer, but using a build script, in Travis-CI and you can remove a deps of `kahlan` inside of `set` in ex.

**Comment by jails** [comment]
You mean creating a custom autoloader script & removing `"required-dev"` in these packages ?

**Comment by m1ome** [comment]
Yes.

**Comment by m1ome** [comment]
You have tow ways:

1. Create a custom autoloader and use something like sub-modules in git.
2. Fetch a kahlan repository with a bash script, instead of composer (with deps)

**Comment by jails** [comment]
My first idea was to make a kind of `composer-install.sh` which correctly set the `COMPOSER_ROOT_VERSION` env var to the `set` version required by Kahlan before running `composer install`.
I guess both solutions will work, just need to clear up my mind up regarding to the base namespace to use for dependencies. I'm fine the actual namespaces but I don't want to put people in trouble. And in another hand, I kindda hate to see some kind of `use billclinton\...`, `use spongebob\...` thingy in my code. Wondering if it would be possible to hit two bird with one stone using composer virtual package behavior https://devedge.wordpress.com/2014/09/27/composer-and-virtual-packages/

**Comment by jails** [comment]
The minimum stability has been removed in 1.1.3

**Comment by m1ome** [comment]
:+1: awesome!
