### ISSUE TITLE
[dev] \plugin\Stub

### ISSUE THREAD

**Issue by m1ome** [crysalead/kahlan#30]
In `plugin\Stub.php` we have a function `_generateParameters`. I have a question, there is a lines: https://github.com/crysalead/kahlan/blob/master/src/plugin/Stub.php#L479-L486

```php
if ($parameter->isOptional()) {
    if ($parameter->isDefaultValueAvailable()) {
        $default = var_export($parameter->getDefaultValue(), true);
    } else {
        $default = 'null';
    }
    $default = ' = ' . preg_replace('/\s+/', '', $default);
}
```

I don't get, hot it could be **optional** and don't have a default value. Opposite situation i can handle, but i don't know any idea when should this line: https://github.com/crysalead/kahlan/blob/master/src/plugin/Stub.php#L483 have been fired.

**Comment by jails** [comment]
The goal was to make all required parameters optional when stubbed. Indeed since stubbed methods are generally intended to be replace with logic like `function() {return true;}`. It doesn't makes sense to have to deal with some "required parameters". I fixed the logic here https://github.com/crysalead/kahlan/commit/7393352013cbf741abdae9d85881c581e3813e17

**Comment by m1ome** [comment]
:+1: ok
