### ISSUE TITLE
Stub in one spec affecting another spec testing the class that had been stubbed

### ISSUE THREAD

**Issue by markcviva** [crysalead/kahlan#59]
I've been experiencing a problem with stubs of a class in one spec affecting another spec testing the class itself which has me wondering if I'm following best practices for writing specs. Consider the following code for two example spec files using Monolog purely for demonstration:

```php
/* filename: spec/MonologStubbingSpec.php */
use kahlan\plugin\Stub;
describe('MonologStubbing', function () {
    it('has a dummy expectation', function () {
        $stubbed_logger = Stub::create(['class' => 'Monolog\Logger']);
        expect(true)->toBe(true);
    });
});
```
```php
/* filename: spec/MonologUsingSpec.php */
describe('MonologUsing', function () {
    it('calls addRecord', function () {
        $logger = new Monolog\Logger('test');
        expect($logger)->toReceive('addRecord');
        $logger->addInfo('test message');
    });
});
```
Running the MonologUsing spec on its own passes but when the specs are run together, it fails. Debugging in the spec/MonologUsingSpec.php with a breakpoint after the call to `addInfo` reveals the following:
With focus
![with focus](http://i.imgur.com/elN8TNz.png)
Without focus
![without focus](http://i.imgur.com/aOyW4EJ.png)
I've managed to work around it by using 'extends' instead of 'class' but I would imagine that this is a common scenario. Is this not an intended use of kahlan? Or is there something I'm missing like forgetting something in a teardown?

**Comment by jails** [comment]
One of PHP assumptions is that once you define a function/constant/class it stays defined forever. So if monkey patching is possible with Kahlan is because hardcoded reference are replaced "Just In Time" by "configurable variables" under the wood. But there's no way to overcome PHP assumptions right from the origin since Kahlan is runned through the PHP interpreter.

So if you do:
```php
$stubbed_logger1 = Stub::create(['class' => 'Monolog\Logger']);
$stubbed_logger2 = Stub::create(['class' => 'Monolog\Logger']);
```
PHP will complain that `Monolog\Logger` has already been declared and you can't declare it again. So that's the limitation of the system and there's no workaround for it.

However Kahlan take care of stub naming collisions out of the box so using `'extends'` is the way to go to play with stubs. Btw hardcoding the class name of a stub has a very few use cases in practice. So if you do you will need to take care of naming collisions by yourself. For example like this:

```php
$stubbed_logger = Stub::create([
    'class' => 'MyMonologStub'
    'extends' => 'Monolog\Logger'
]);
```

In your previous example, doing `$stubbed_logger = Stub::create(['class' => 'Monolog\Logger']);` creates the `Monolog\Logger` class. So in the second spec, since `Monolog\Logger` was defined, the autoloader just bailed out and uses the defined `Monolog\Logger` class which was actually the stub.

Just keep in mind that even with Kahlan, PHP assumptions still applies. Kahlan just offer a way to play with hardcoded dependencies by switching implementations on the fly.

**Comment by markcviva** [comment]
Ah, understood. It was clear what was happening but I had some hope that there would be a way around it. I was using hard-coded references to try to accurately reflect what was being expected even if it effectively didn't mean much. I'll keep it in mind when writing future specs. Thanks for the reply.
