### ISSUE TITLE
Сode coverage report in HTML format?

### ISSUE THREAD

**Issue by ilsenem** [crysalead/kahlan#78]
There is a possibility that there will be native support for generating code coverage report in HTML format?

If not, can you give a tip how to achieve this?

P.S. You have made a great tool, thank you! Already using it in my projects.

**Comment by jails** [comment]
Unfortunately there's no built in code coverage report in HTML yet. I delegated this job to external services like Scrutinizer, Coveralls or Code Climate.

However it's definitly possible to create a exporter to generate an HTML report.
First you should take a look at the repo [config file](https://github.com/crysalead/kahlan/blob/07ba246b0517e7d18a0d0c1664a1e75e9293521c/kahlan-config.travis.php#L46-L66)

This is how I'm exporting the code coverage result into a different format for the different services. Line 46 I'm registering the logic and line 66 make it executed at the `'reporting'` step.

The object you will need to extract data from is:

```php
    $reporter = $this->reporters()->get('coverage');
```

The coverage reporter should contain all the data you need to build your reporter. To get file's covered lines you can do the following:

```php
$collector = $reporter->collector();
foreach ($collector->export() as $file => $data) {
    // $file is a filepath
    // $data is an array where the key is a line number and the value is the
    // number of times the line has been covered
}
```
Other usefull data are the metrics. Metrics are statistics related to method, classes and namespaces.

To get coverage metrics you can use the following:
```php
$metrics = $reporter->metrics();
$metrics->data(); //returns the global metrics
$metrics->get('some\name\space')->data(); //returns namespace metrics
$metrics->get('some\name\space\ClassName')->data(); //returns class metrics
$metrics->get('some\name\space\ClassName::helloWorld()')->data(); //returns method metrics
```

By the way from a metrics you can access all child metrics through `$metrics->childs()`.

There's some [specs](https://github.com/crysalead/kahlan/tree/master/spec/suite/reporter/coverage) which may help to get the API.

Otherwise you can check the [default textual representation of metrics](https://github.com/crysalead/kahlan/blob/3e4d2d13ebc9933604e19bfba90fc82eec5a11e7/src/reporter/Coverage.php#L167-L189) in the coverage reporter.

Hope that helps.

**Comment by ilsenem** [comment]
It helped a lot, thanks.

I need to be less lazy and dig into code next time. :smile:

**Comment by jails** [comment]
You're welcome ;-)

**Comment by jails** [comment]
This feature is now available through istanbul using the `--istanbul` option:
```
npm install -g istanbul
./bin/kahlan --istanbul=coverage.json
istanbul report
```
the HTML code coverage report will be in `coverage/lcov-report/index.html`.
