### ISSUE TITLE
constructor override

### ISSUE THREAD

**Issue by jarektkaczyk** [crysalead/kahlan#95]
Tried to override `__construct` to empty function according to this:

https://github.com/crysalead/kahlan/blob/master/src/plugin/Stub.php#L185

but apparently it's irrelevant now, since it seems not to be used anywhere in the code.

However, using `magicMethods => true` solved the issue, so please review the comment and I guess it would be nice to include such example in the docs http://kahlan.readthedocs.org/en/latest/stubs/#class-stubbing.

Anyway thanks for the breath of fresh air in php testing!

**Comment by jails** [comment]
Good catch, fixed in https://github.com/crysalead/kahlan/commit/122e03a07e17bb65ef710b3f67f98471d8369a48
This parameter has been removed in flavor of the following syntax `'methods' => ['__construct']` which should works for any kind of method.

Glad you like Kahlan, I'm using it since 2 years and it already saved me a lot of time.
